- name: vm_admin_user
  title: VM Admin Username
  description: Username for the VM SSH login
  required: true

- name: vm_admin_password
  title: VM Admin Password
  description: Password for the VM SSH login
  required: true

- name: ssh_public_key
  title: SSH Public Key
  description: Paste your SSH public key to access the virtual machine via SSH
  required: true

